version: v1alpha1
clusters:
  - name: hubartem
    stage: dev
    type: hub
    dnsName: hubartem-dev.stackit.run
    ssoOrg: la-demos
    ssoTeam: g-gitops
    ingressClassName: traefik
    terraform:
      provider: stackit
      projectId: 38867e9e-b5d4-4a85-97a8-0a944ab75b19
      kubernetesType: ske
      kubernetesVersion: "1.35"
      dns:
        name: hubartem-dev.stackit.run
        email: artem.lajko@iits-consulting.de
    argocd:
      repo:
        https:
          customer:
            url: https://github.com/la-cc/kubara-local.git
            targetRevision: main
          managed:
            url: https://github.com/la-cc/kubara-local.git
            targetRevision: main
    services:
      argocd:
        status: disabled
      cert-manager:
        status: enabled
        config:
          clusterIssuer:
            email: artem.lajko@iits-consulting.de
            name: letsencrypt-staging
            server: https://acme-staging-v02.api.letsencrypt.org/directory
      external-dns:
        status: enabled
      external-secrets:
        status: enabled
      homer-dashboard:
        status: enabled
      kube-prometheus-stack:
        status: enabled
      kyverno:
        status: enabled
      kyverno-policies:
        status: enabled
      kyverno-policy-reporter:
        status: enabled
      loki:
        status: enabled
      longhorn:
        status: disabled
      metallb:
        status: disabled
      metrics-server:
        status: disabled
      oauth2-proxy:
        status: enabled
      traefik:
        status: enabled
