clusterIssuer:
  name: letsencrypt-staging
  email: artem.lajko@iits-consulting.de
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  ingressClassName: traefik


cert-manager:
  global:
    imagePullSecrets:
      - name: image-pull-secret
  prometheus:
    servicemonitor:
      enabled: true
      labels:
        monitoring.instance: hubartem-dev

namespace:
  labels:
    project-name: "hubartem"
    stage: "dev"
